Cpd identical code
parameterIT/tool pull request #23
Opened 2023-02-23 11:47 UTC by Kobo-coder

## Describe your changes

Added POC code for identical code scanning using copy paste detector (cpd)

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Have I requested and notified the boys for review of the pull-request?

2023-02-24 10:06 UTC, FrederikRothe commented on pyproject.toml
>  python = "^3.11"
This will most likely be a merge conflict no?

2023-02-24 10:07 UTC, FrederikRothe requested changes
Merge conflicts, but otherwise looks good 👍🏼

2023-02-24 14:50 UTC, toffernator commented
> ## Describe your changes
> 
> Added POC code for identical code scanning using copy paste detector (cpd)
> 
> I want to add the following: I find it difficult to understand how cpd counts duplicates. I can up until 1 and 2 comfortably determine how many duplicates will appear, but upon reaching what I would have thought would be 3, the actual value differs. This makes it incredibly difficult to test. Though for a POC this might be okay, but we will need a way to interpret the count of duplicates it returns.
> ## Checklist before requesting a review
> 
>     * [x]  I have performed a self-review of my code.
> 
>     * [x]  If it is a core feature, I have added thorough tests.
> 
>     * [x]  Have I requested and notified the boys for review of the pull-request?

Can we add a task to better understand and add more tests for this?

2023-02-27 07:34 UTC, toffernator approved these changes

2023-02-27 07:35 UTC, merged